import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "./component/header";
import Sider from "./component/sider";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-TW">
      <body className="flex flex-row justify-start w-full gap-4 p-4">
        <Sider />
        <div className="w-full ">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
